### ISSUE TITLE
`qubes-u2fproxy.service` crashing on Debian

### ISSUE THREAD

**Issue by SaswatPadhi** [QubesOS/qubes-app-u2f#14]
Currently, I see the following status:

```
user@primary ~> sudo systemctl status qubes-u2fproxy.service
● qubes-u2fproxy.service
   Loaded: loaded (/lib/systemd/system/qubes-u2fproxy.service; indirect; vendor preset: enabled)
   Active: inactive (dead)

Sep 22 16:32:20 primary systemd[1]: /lib/systemd/system/qubes-u2fproxy.service:2: Unknown lvalue 'Descripts' in section 'Unit', ignoring
Sep 22 16:34:36 primary systemd[1]: /lib/systemd/system/qubes-u2fproxy.service:2: Unknown lvalue 'Descripts' in section 'Unit', ignoring
```

After fixing `Descripts` → `Description` in [`qubes-u2fproxy.service`](https://github.com/QubesOS/qubes-app-u2f/blob/master/systemd/qubes-u2fproxy.service#L2):

```
user@primary ~> sudo systemctl status qubes-u2fproxy.service
● qubes-u2fproxy.service - Default instance of qubes-u2f-proxy
   Loaded: loaded (/lib/systemd/system/qubes-u2fproxy.service; indirect; vendor preset: enabled)
   Active: inactive (dead)

Sep 22 16:32:20 primary systemd[1]: /lib/systemd/system/qubes-u2fproxy.service:2: Unknown lvalue 'Descripts' in section 'Unit', ignoring
Sep 22 16:34:36 primary systemd[1]: /lib/systemd/system/qubes-u2fproxy.service:2: Unknown lvalue 'Descripts' in section 'Unit', ignoring
Sep 22 16:34:40 primary systemd[1]: /lib/systemd/system/qubes-u2fproxy.service:2: Unknown lvalue 'Descripts' in section 'Unit', ignoring
Sep 22 16:36:02 primary systemd[1]: Starting Default instance of qubes-u2f-proxy...
Sep 22 16:36:02 primary systemd[1]: qubes-u2fproxy.service: Succeeded.
Sep 22 16:36:02 primary systemd[1]: Started Default instance of qubes-u2f-proxy.
```

**Comment by marmarek** [comment]
What is the actual problem? Besides (harmless) typo, I don't anything wrong here.
Note the actual running service is `qubes-u2fproxy@sys-usb.service`, `qubes-u2fproxy.service` is only starting it indirectly.

**Comment by SaswatPadhi** [comment]
No, `qubes-u2fproxy@sys-usb.service` was never started with the buggy unit. Only after fixing the typo, the `qubes-u2fproxy@sys-usb.service` was able to start. You could test it on a Debian AppVM

**Comment by marmarek** [comment]
That must have be a different reason. Just verified it works as expected on debian-10. Have you followed https://www.qubes-os.org/doc/u2f-proxy/#installation ? Especially `qvm-service --enable ... qubes-u2f-proxy` step?

**Comment by SaswatPadhi** [comment]
Aha! Thank you. I just checked `qvm-service` for my VM and I had made a typo: "qubes-u2f-prox" instead of "qubes-u2f-proxy". I thought this typo was the issue and as a workaround I was fixing the typo and restarting the service in my `rc.local`, but the real culprit was my typo!

Thanks again :)
